version: '3.8'

services:
  stable-diffusion-webui:
    image: stable-diffusion-rocm:1.2
    build:
      context: docker
      args:
        DOCKER_BUILDKIT: 1
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    ipc: host
    security_opt:
      - seccomp:unconfined
    network_mode: "host"
    stop_signal: SIGINT
    stdin_open: true
    tty: true
    shm_size: '8gb'
    volumes:
      - ./data:/data:rw
volumes:
  data:
